# Generated by Django 3.1.3 on 2020-11-25 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forest', '0003_auto_20201125_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='host',
        ),
        migrations.RemoveField(
            model_name='post',
            name='host',
        ),
    ]
